# Generated by Django 5.2.1 on 2026-05-13 14:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_created_at_alter_member_email_and_more'),
        ('memberships', '0002_alter_membership_created_at_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='members.member', verbose_name='Üye'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='memberships.membership', verbose_name='Üyelik'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='note',
            field=models.TextField(blank=True, verbose_name='Not'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Ödeme tarihi'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Nakit'), ('CARD', 'Kart')], default='CASH', max_length=20, verbose_name='Ödeme yöntemi'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi'),
        ),
    ]
