# Generated by Django 5.2.1 on 2026-05-15 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_created_at_alter_member_email_and_more'),
        ('memberships', '0006_alter_membership_member_alter_membership_status'),
        ('payments', '0002_alter_payment_amount_alter_payment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='members.member', verbose_name='Üye'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='memberships.membership', verbose_name='Üyelik'),
        ),
    ]
