# Generated by Django 5.2.1 on 2026-05-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_member_alter_payment_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Geçerli'), ('VOIDED', 'İptal Edildi')], default='ACTIVE', max_length=20, verbose_name='Kayıt durumu'),
        ),
        migrations.AddField(
            model_name='payment',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='İptal tarihi'),
        ),
    ]
