# Generated by Django 5.2.1 on 2026-05-13 15:42

from django.db import migrations, models


def normalize_custom_user_roles(apps, schema_editor):
    CustomUser = apps.get_model("accounts", "CustomUser")
    CustomUser.objects.all().update(role="ADMIN", is_staff=True)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_email_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "Yönetici")],
                default="ADMIN",
                max_length=20,
                verbose_name="Rol",
            ),
        ),
        migrations.RunPython(normalize_custom_user_roles, migrations.RunPython.noop),
    ]
