# Generated by Django 5.2.1 on 2026-05-13 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_created_at_alter_member_email_and_more'),
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Bitiş tarihi'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='members.member', verbose_name='Üye'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notlar'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='memberships.membershipplan', verbose_name='Paket'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='start_date',
            field=models.DateField(verbose_name='Başlangıç tarihi'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Aktif'), ('EXPIRED', 'Süresi Doldu'), ('PAUSED', 'Askıda'), ('CANCELLED', 'İptal')], default='ACTIVE', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='description',
            field=models.TextField(blank=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='duration_days',
            field=models.PositiveIntegerField(verbose_name='Süre (gün)'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Paket adı'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi'),
        ),
    ]
