# Generated by Django 5.2.1 on 2026-05-13 15:42

from django.db import migrations, models


def populate_agreed_price(apps, schema_editor):
    Membership = apps.get_model("memberships", "Membership")
    for membership in Membership.objects.select_related("plan").all():
        membership.agreed_price = membership.plan.price
        membership.save(update_fields=["agreed_price"])


class Migration(migrations.Migration):

    dependencies = [
        ("memberships", "0002_alter_membership_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="agreed_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Üyelik ücreti",
            ),
        ),
        migrations.RunPython(populate_agreed_price, migrations.RunPython.noop),
    ]
