# Generated by Django 5.2.1 on 2026-05-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_membership_agreed_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='agreed_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Üyelik ücreti'),
        ),
    ]
