# Generated by Django 5.2.1 on 2026-05-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_alter_membership_agreed_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='freeze_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Dondurma bitişi'),
        ),
        migrations.AddField(
            model_name='membership',
            name='freeze_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Dondurma başlangıcı'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Aktif'), ('EXPIRED', 'Süresi Doldu'), ('PAUSED', 'Donduruldu')], default='ACTIVE', max_length=20, verbose_name='Durum'),
        ),
    ]
