# Generated by Django 5.2.1 on 2026-05-15 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_created_at_alter_member_email_and_more'),
        ('memberships', '0005_membership_freeze_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='members.member', verbose_name='Üye'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planlandı'), ('ACTIVE', 'Aktif'), ('EXPIRED', 'Süresi Doldu'), ('PAUSED', 'Donduruldu')], default='ACTIVE', max_length=20, verbose_name='Durum'),
        ),
    ]
