# Generated by Django 5.2.1 on 2026-05-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0006_alter_membership_member_alter_membership_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='membershipplan',
            constraint=models.CheckConstraint(condition=models.Q(('duration_days__gt', 0)), name='membership_plan_duration_days_positive'),
        ),
        migrations.AddConstraint(
            model_name='membershipplan',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='membership_plan_price_positive'),
        ),
    ]
